#!/usr/bin/env python3
"""Turn the shared .map files into src/maps.h.

The C64 build has no file system to load from, so the maps become const
arrays in the program. Run `make maps` after changing assets/maps/*.map.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MAPS = [("village", ROOT / "assets/maps/village.map"),
        ("forest", ROOT / "assets/maps/forest.map")]
OUT = pathlib.Path(__file__).resolve().parents[1] / "src/maps.h"


def read(path):
    lines = path.read_text().splitlines()
    width, height = (int(n) for n in lines[0].split())
    rows = lines[1:1 + height]
    if len(rows) != height or any(len(r) != width for r in rows):
        sys.exit(f"{path}: rows do not match {width}x{height}")
    return width, height, rows


def main():
    out = ["/* Generated by tools/genmaps.py from assets/maps -- do not edit. */",
           "#ifndef MAPS_H", "#define MAPS_H", ""]
    for name, path in MAPS:
        width, height, rows = read(path)
        out.append(f"#define {name.upper()}_W {width}")
        out.append(f"#define {name.upper()}_H {height}")
        out.append(f"static const char {name}_cells[] = ")
        for row in rows:
            out.append(f'    "{row}"')
        out[-1] += ";"
        out.append("")
    out += ["#endif", ""]
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
