#!/usr/bin/env python3
"""Turn the shared .map files into src/maps.h.

The C64 build has no file system to load from, so the maps become const
arrays in the program. Run `make maps` after changing assets/maps/*.map.

Die Zellen liegen lauflaengenkodiert im Programm: beide Karten sind 2688
Zeichen, von denen die meisten Wiederholungen sind (`.`, `h`, `s`, `^`, `,`).
Ein Byte mit gesetztem Hoechstbit wiederholt das folgende Zeichen, jedes andere
Byte ist ein einzelnes Zeichen; `*_rows` sagt, wo eine Zeile anfaengt, damit
eine einzelne Zeile ohne Suchen auspackbar bleibt. Ausgepackt wird in world.c.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MAPS = [("village", ROOT / "assets/maps/village.map"),
        ("forest", ROOT / "assets/maps/forest.map")]
OUT = pathlib.Path(__file__).resolve().parents[1] / "src/maps.h"

RUN = 0x80  # Hoechstbit im Zaehlerbyte: Wiederholung statt Einzelzeichen
MIN_RUN = 3  # kuerzere Laeufe kosten als Einzelzeichen nicht mehr


def read(path):
    lines = path.read_text().splitlines()
    width, height = (int(n) for n in lines[0].split())
    rows = lines[1:1 + height]
    if len(rows) != height or any(len(r) != width for r in rows):
        sys.exit(f"{path}: rows do not match {width}x{height}")
    return width, height, rows


def encode(row, path):
    """Eine Kartenzeile als Folge von Einzelzeichen und Wiederholungen."""
    out = bytearray()
    i = 0
    while i < len(row):
        j = i
        while j < len(row) and row[j] == row[i] and j - i < RUN - 1:
            j += 1
        length = j - i
        if ord(row[i]) >= RUN:
            sys.exit(f"{path}: {row[i]!r} ist kein ASCII-Zeichen")
        if length >= MIN_RUN:
            out += bytes((RUN | length, ord(row[i])))
        else:
            out += row[i].encode("ascii") * length
        i = j
    if len(out) > len(row):
        # Kaeme nie vor, solange die Karten Flaechen haben; dann waere aber die
        # Zeilenlaenge nicht mehr die obere Grenze fuer den Auspackpuffer.
        sys.exit(f"{path}: Zeile waechst beim Kodieren ({len(out)} > {len(row)})")
    return bytes(out)


def main():
    raw = coded = index = 0
    out = ["/* Generated by tools/genmaps.py from assets/maps -- do not edit. */",
           "#ifndef MAPS_H", "#define MAPS_H", "#include <stdint.h>", "",
           "/* Lauflaengenkodiert: ein Byte mit gesetztem Hoechstbit wiederholt das",
           " * folgende Zeichen (Anzahl in den unteren sieben Bit), jedes andere Byte",
           " * ist ein einzelnes Zeichen. *_rows nennt den Anfang jeder Zeile im",
           " * Strom. Die Kommentare zeigen die Zeile, wie sie in assets/maps steht. */",
           ""]
    for name, path in MAPS:
        width, height, rows = read(path)
        encoded = [encode(row, path) for row in rows]
        offsets, at = [], 0
        for chunk in encoded:
            offsets.append(at)
            at += len(chunk)
        raw += width * height
        coded += at
        index += 2 * height
        out.append(f"#define {name.upper()}_W {width}")
        out.append(f"#define {name.upper()}_H {height}")
        out.append(f"static const uint16_t {name}_rows[{name.upper()}_H] = {{")
        for i in range(0, len(offsets), 12):
            out.append("    " + " ".join(f"{o}," for o in offsets[i:i + 12]))
        out.append("};")
        out.append(f"static const uint8_t {name}_cells[] = {{")
        for row, chunk in zip(rows, encoded):
            out.append(f'    /* "{row}" */')
            out.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
        out.append("};")
        out.append("")
    out += ["#endif", ""]
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}: {raw} Zellen -> {coded} Bytes + {index} Bytes Zeilentabelle")


if __name__ == "__main__":
    main()
